services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128Mb
    environment:
      POSTGRES_USER: zavodchat
      POSTGRES_DB: zavodchat
      POSTGRES_PASSWORD: q1w2e3
    ports:
      - 5433:5432

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - upload-volume:/data
    ports:
      - 443:443 # HTTPS 
      - 444:444 # Main socket
      - 445:445 # VC socket
      - 50000:50000/udp # WebRTC

volumes:
  upload-volume:
